#!/bin/bash
rm -rf pspbuild
mkdir pspbuild
cd pspbuild
psp-cmake .. -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=TRUE -DBUILD_CPU_DEMOS=OFF -DBUILD_OPENGL3_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_UNIT_TESTS=OFF
make VERBOSE=1 install

